### ISSUE TITLE
Please publish to npmjs

### ISSUE THREAD

**Issue by diguasen** [yuko1101/enka-network-api#1]
We need this api to publish to npmjs，thanks!

**Comment by diguasen** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/652

**Comment by diguasen** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/652#issuecomment-1260571525

**Comment by yuko1101** [comment]
Thank you for your issue! (And sorry for late answer.)
We've published to npm, and now you can install our package with command `npm i enka-network-api`.

If you have any other questions or problems, feel free to open issues.
