### ISSUE TITLE
Artifact substat type doesnt match the actual object

### ISSUE THREAD

**Issue by blobnom** [yuko1101/enka-network-api#10]
https://github.com/yuko1101/enka-network-api/blob/14926aa734bca05c3fd35e835bc79bb03dbb08be/src/models/artifact/Artifact.js#L45

**Comment by yuko1101** [comment]
Oh, thanks for your issue.
I will fix it right away

**Comment by yuko1101** [comment]
The change is available from version 1.6.12.

**Comment by yuko1101** [comment]
Sorry, I didn't fixed completely.
I just fixed it. (318926eac374f080e8fb795f500a3adc8741f13a)
And changed type def to better one. (3ec04675178c53405bf1069a7922473317f0543a)
