### ISSUE TITLE
Method getAllArtifacts ?

### ISSUE THREAD

**Issue by Gus19** [yuko1101/enka-network-api#11]
Hello !

First, thanks for this very nice wrapper :grin: !

Like allCharacters and allWeapons, is it possible to list all the artifacts ?

And why node>=16 for the requirements ?

Thanks !

**Comment by yuko1101** [comment]
> Like allCharacters and allWeapons, is it possible to list all the artifacts ?

Nice idea. I will give it a try.

> And why node>=16 for the requirements ?

That's because I didn't test it on node 15
and node 14 or earlier don't have some operators (such as "??=").

If you wish to use node 15, I will test on node 15.

**Comment by Gus19** [comment]
Cool ! Good luck :grin: 

I'm currently with node 14, didn't know this operator.
No need, I will update my version.

**Comment by yuko1101** [comment]
Added, but not released yet.
Cuz I didn't test it well, and some changes are WIP.

If you would like to use EnkaClient#getAllArtifacts, 
please install it from github with `npm i yuko1101/enka-network-api`.

**Comment by Gus19** [comment]
It's works fine !
But recent sets are not present ?

- Deepwood Memories
- Echoes of an Offering
- Emblem of Severed Fate
- Gilded Dreams
- Husk of Opulent Dreams
- Ocean-Hued Clam
- Shimenawa's Reminiscence
- Vermillion Hereafter
- Desert Pavilion Chronicle
- Flower of Paradise Lost

**Comment by yuko1101** [comment]
Oh wait, I will fix it if possible.

**Comment by yuko1101** [comment]
Probably fixed. b721f8fffa12cf0f55757c7ca90192659b0f05a5

**Comment by Gus19** [comment]
Perfect :+1:

**Comment by yuko1101** [comment]
`getAllArtifacts` method will be available from version 1.11.0
