### ISSUE TITLE
avatar Icon 404 Not found.

### ISSUE THREAD

**Issue by KhsDev** [yuko1101/enka-network-api#125]
Hello!

enka-network-api  4.2.0

```javascript
const user = await enka.fetchUser("uid")
console.log(user.profilePicture.costume.icon.url)
```
```
https://api.ambr.top/assets/UI/UI_AvatarIcon_GanyuCostumeYu.png // res 404 Not Found
``` 
![image](https://github.com/yuko1101/enka-network-api/assets/153170677/9ee9fce1-a97f-4919-bbdd-5bfc5b3bba75)

**Comment by yuko1101** [comment]
I will change the urls in the lib if ambr doesn't fixed it 👍

**Comment by yuko1101** [comment]
https://api.ambr.top/assets/UI/UI_AvatarIcon_GanyuCostumeYu.png
is now available

thanks again for reporting
