### ISSUE TITLE
Buffer is not defined error 

### ISSUE THREAD

**Issue by Amedast** [yuko1101/enka-network-api#23]
Hello! 

Im trying to use your wrapper with a React app and when I import it I got "Uncaught ReferenceError: buffer is not defined", am I doing something wrong?
![Captura de pantalla 2023-03-18 234846](https://user-images.githubusercontent.com/114661034/226144063-51e54117-2983-44a5-89cd-e3b1a3a806e0.png)
![Captura de pantalla 2023-03-18 234923](https://user-images.githubusercontent.com/114661034/226144153-da08e29f-4322-435b-ba36-34a5106543dd.png)
Thanks in advance :)

**Comment by yuko1101** [comment]
Thanks for your issue.

I'm sorry but this wrapper only works on backend.
Try to create a backend server with the wrapper, and send the data to frontend.
