### ISSUE TITLE
 CharacterAscension data was not found

### ISSUE THREAD

**Issue by HirziDevs** [yuko1101/enka-network-api#24]
Hello i want to get character accession data but i got this error
````js
        if (!this._data) throw new AssetsNotFoundError("CharacterAscension", `${id}-${ascension}`);
                         ^
AssetsNotFoundError: CharacterAscension 46-20 was not found. Try to update cached assets with EnkaClient#cachedAssetsManager#fetchAllContents
````
i already add `EnkaClient#cachedAssetsManager#fetchAllContents` to my code but still getting the error
```js
const { EnkaClient } = require("enka-network-api");

const enka = new EnkaClient({ cacheDirectory: "./cache" });

enka.cachedAssetsManager.cacheDirectorySetup();
enka.cachedAssetsManager.fetchAllContents();

const character = enka.getCharacterById(10000046)
console.log(character.name.get('id'))

const ascend = character.getAscensionData(20)
console.log(ascend)
````

**Comment by yuko1101** [comment]
Thank you for your issue.

Try `character.getAscensionData(1)`.
It requires ascension level, not character level.

**Comment by HirziDevs** [comment]
ahh i was doing it wrong, thank you for answering!, also can you add getTalentData method? like getAscensionData?

**Comment by yuko1101** [comment]
There is [UpgradableSkill#getSkillAttributes](https://enka-network-api.vercel.app/docs/api/UpgradableSkill#getSkillAttributes) and [UpgradableSkill#getUpgradeCost](https://enka-network-api.vercel.app/docs/api/UpgradableSkill#getUpgradeCost).
These are not enough?

**Comment by HirziDevs** [comment]
thats enough thanks!
