### ISSUE TITLE
Getting undefined 'nickname' from EnkaClient.js on fetchUser

### ISSUE THREAD

**Issue by TsumikiVR** [yuko1101/enka-network-api#25]
Getting this error on every users I try
![image](https://user-images.githubusercontent.com/49730009/229159082-e7bbf9e0-02a9-443b-8123-df2a95aa31f1.png)

**Comment by yuko1101** [comment]
Thank you for your issue.

What enka-network-api version are you using?
Bringing the package up to date may solve the problem.

**Comment by TsumikiVR** [comment]
Sorry for the late reply,
I was using v1.9.6, `"enka-network-api":*` was hiding me the real current version, getting it up to date fixed the issue.
Thank you
