### ISSUE TITLE
Profile card icon not found

### ISSUE THREAD

**Issue by JokelBaf** [yuko1101/enka-network-api#31]
Hello!

This code
```typescript
const user = await enka.fetchUser(123456789, false) as DetailedUser;
console.log(user.profileCard.icon.url);
```
Logs this url
```
https://api.ambr.top/assets/UI/UI_NameCardIcon_Cyno.png
```
But this page does not exist... Am I doing something wrong?

**Comment by yuko1101** [comment]
Thank you for your issue.

I'm sorry. I have just fixed it in the latest version (3.0.2).
Please update the package and try again.

```sh-session
npm i enka-network-api@latest
```
