### ISSUE TITLE
【Emergency】Cannot access the enka!

### ISSUE THREAD

**Issue by Georgebillion** [yuko1101/enka-network-api#5]
I can not access the Enka to update my infos.I try to access by Browser But it call 529 error about SSL certificate,How should I do?

**Comment by Georgebillion** [comment]
![image](https://user-images.githubusercontent.com/40432824/198877779-48ec1155-9b76-4e6c-b3b1-3417031a1b5c.png)
Update pic for u

**Comment by yuko1101** [comment]
It's a problem with Enka.Network.
The server seems to be down at the moment.

All you can do is wait until the problem is resolved.

**Comment by yuko1101** [comment]
Now, the server is back!
