### ISSUE TITLE
Artifacts issues

### ISSUE THREAD

**Issue by gamersindo1223** [yuko1101/enka-network-api#7]
hello i got this error when doing
`const { EnkaClient } = require("enka-network-api");
const enka = new EnkaClient();

enka.fetchUser(858576029).then(user => {
  console.log(user);
});`
and when i go to 
Artifact.js and remove line 48 it didn't show any error!

The error `D:\coding-essentials\project\Discord.js-v14\node_modules\enka-network-api\src\models\artifact\Artifact.js:48
            split: data.reliquary.appendPropIdList.map(id => new ArtifactSplitSubstat(id, enka)),
                                                   ^

TypeError: Cannot read properties of undefined (reading 'map')`

**Comment by Algoinde** [comment]
Valid. `appendPropIdList` is not guaranteed to exist in case the artifact has zero substats.

**Comment by yuko1101** [comment]
Thank you for your issue.

We've just fixed the issue with version 1.6.4.
You can install the latest version via npmjs.
